-- Expert distractors for the existing bank, plus new questions with a full
-- obvious / plausible / tricky ladder. Apply after the app reads choices.tier.
insert into ltf.choices (question_id, label, body, is_correct, rationale, sort_order, tier)
select q.id, 'D', v.body, false, v.rationale, v.sort_order, 3
from ltf.questions q join (values
  ('oop-category-1-rotating-parts', 'A label identifying it as eligible for Category 1 operations', 'Only Category 2 and 3 aircraft must carry an eligibility label. Category 1 has no labeling requirement.', 4),
  ('oop-category-1-weight', '0.55 pounds or less, not counting the battery', 'The weight includes everything on board or attached at takeoff, battery included.', 4),
  ('oop-category-2-energy', '15 foot-pounds', 'No category uses 15. Category 2 is 11 foot-pounds and Category 3 is 25.', 4),
  ('oop-category-3-energy', '55 foot-pounds', 'Category 3 is 25 foot-pounds. 55 is the pound limit for a small unmanned aircraft, not an energy figure.', 4),
  ('oop-category-3-restrictions', 'Only over people who have signed a written consent form', 'Category 3 turns on a closed site where everyone is on notice, or no sustained flight over people. Written consent is not the test.', 4),
  ('oop-category-4', 'It has an FAA-accepted declaration of compliance', 'A declaration of compliance is the Category 2 and 3 route. Category 4 needs a Part 21 airworthiness certificate.', 4),
  ('oop-damaged-label', 'Carry a printed copy of the declaration of compliance in place of the label', 'The label belongs on the aircraft. If it is unreadable, the remote pilot must re-label it before the operation.', 4),
  ('oop-declaration-of-compliance', 'A record accepted by the FAA certifying an aircraft is eligible for Category 4', 'Category 4 relies on an airworthiness certificate, not a declaration of compliance.', 4),
  ('oop-means-of-compliance', 'Test and inspection only; analysis is not accepted', '107.155 accepts test, analysis, or inspection, alone or in combination.', 4),
  ('oop-moving-vehicles', 'Remain in a closed site with notice, or stay at least 50 feet above the vehicle', 'There is no altitude alternative. Outside a closed site, flight over moving vehicles must be transient, not sustained.', 4),
  ('oop-open-air-assembly', 'Categories 1 and 2 only, where Remote ID requirements are also met', 'Category 4 may also operate over open-air assemblies. Category 3 is the only category barred.', 4),
  ('oop-variable-modes', 'The remote pilot must notify the FAA before switching modes', 'No notice is required. The design must simply prevent the pilot from switching modes by accident.', 4),
  ('reg-adsb-out-prohibition', 'ADS-B Out is permitted only in Class B or C airspace', '107.53 prohibits ADS-B Out in transmit mode in all airspace unless otherwise authorized.', 4),
  ('reg-alt-400-structure', '1,100 feet AGL, provided you remain within a 500-foot radius of the tower', 'The lateral limit is a 400-foot radius, not 500.', 4),
  ('reg-applicability-exclusions', 'Commercial flights of an aircraft weighing 0.55 pounds or less', 'Part 107 applies to commercial flying at any weight. 0.55 pounds matters for registration exceptions and Category 1, not applicability.', 4),
  ('reg-certificate-possession', 'You must present it, but only if the officer is a federal agent', '107.7 lets federal, state, and local law enforcement officers all request it.', 4),
  ('reg-change-of-address', '14 days', '14 days is the retest wait after a failed knowledge test. The address window is 30 days.', 4),
  ('reg-civil-twilight-definition', 'The period beginning at sunset and ending when the sun is 12 degrees below the horizon', '12 degrees marks nautical twilight. Outside Alaska, Part 107 uses the fixed 30-minute window.', 4),
  ('reg-cloud-clearance', '500 feet below, 1,000 feet above, and 2,000 feet horizontally', 'That is the manned VFR minimum in much of Class E and G. Part 107 sets only 500 feet below and 2,000 feet horizontally.', 4),
  ('reg-controlled-airspace-auth', 'A Certificate of Waiver issued under 107.200', 'Class B, C, D, and surface Class E need ATC authorization under 107.41. A waiver covers waivable rules, not airspace access.', 4),
  ('reg-direct-supervision', 'Under direct supervision, but only after the assistant has passed the knowledge test', 'No test is required. What matters is that the rPIC can immediately take direct control.', 4),
  ('reg-dropping-object', 'Only when the object weighs less than 0.55 pounds', '107.23(b) has no weight test. The test is whether dropping it creates an undue hazard.', 4),
  ('reg-drug-conviction', 'Denial of an application for up to 1 year, with no effect on a certificate already held', '107.57 also allows suspension or revocation of a certificate already held.', 4),
  ('reg-eligibility-age', '16 years old, or 18 to fly for compensation', 'There is no separate age for commercial work. 16 is the single minimum.', 4),
  ('reg-hazmat', 'Yes, with a waiver issued under 107.200', '107.36 is not a waivable section. No waiver can authorize hazardous material under Part 107.', 4),
  ('reg-inflight-emergency', 'The rPIC may deviate from any rule, but must file a written report within 10 days', 'A written report is due only if the Administrator requests one, under 107.21(b).', 4),
  ('reg-knowledge-recency', 'By completing recurrent training within the previous 12 calendar months', 'The recency window is 24 calendar months.', 4),
  ('reg-max-groundspeed', '100 knots (87 miles per hour)', 'The units are swapped. The limit is 87 knots, which is 100 miles per hour.', 4),
  ('reg-medical-condition', 'You may serve as visual observer, but not as rPIC', '107.17 bars you from acting as rPIC, visual observer, or manipulating the controls.', 4),
  ('reg-min-visibility', '5 statute miles, measured from the control station', 'The minimum is 3 statute miles.', 4),
  ('reg-moving-vehicle', 'Only over a sparsely populated area, and only with a visual observer in the vehicle', 'No visual observer is required. The second condition is that you may not carry another person''s property for hire.', 4),
  ('reg-multiple-aircraft', 'Three, provided each weighs 0.55 pounds or less', 'Weight does not change 107.35. One person may operate one aircraft at a time.', 4),
  ('reg-night-lighting', 'Anti-collision lighting visible for at least 5 statute miles', 'The rule sets 3 statute miles.', 4),
  ('reg-over-human-beings', 'A person inside a moving vehicle with a hard roof', 'The exception covers a covered structure or a stationary vehicle. A moving vehicle is treated separately.', 4),
  ('reg-preflight-assessment', 'Local weather and airspace, plus a written weight and balance computation', '107.49 requires assessing weather, airspace, and people and property on the surface. No weight and balance computation is mandated.', 4),
  ('reg-refusal-alcohol-test', 'Automatic, permanent revocation of the certificate', '107.59 allows denial for up to 1 year, or suspension or revocation. Nothing is automatic or permanent.', 4),
  ('reg-restricted-area-permission', 'Permission from the nearest Flight Standards District Office', 'The using or controlling agency grants access, not an FSDO.', 4),
  ('reg-retest-after-failure', '7 calendar days', 'The wait is 14 calendar days.', 4),
  ('reg-right-of-way', 'The small unmanned aircraft yields only to manned aircraft in controlled airspace', '107.37 requires yielding to all aircraft, in any airspace.', 4),
  ('reg-rpic-final-authority', 'The visual observer, while the aircraft is out of the rPIC''s sight', 'Final authority never transfers to a visual observer.', 4),
  ('reg-safety-event-threshold', 'A report to the FAA within 30 calendar days', 'The window is 10 calendar days.', 4),
  ('reg-safety-event-window', 'Within 10 business days', 'The rule counts calendar days, not business days.', 4),
  ('reg-suas-definition-weight', '55 pounds or less on takeoff, including everything on board', 'A small unmanned aircraft weighs less than 55 pounds. Exactly 55 is not small.', 4),
  ('reg-temporary-certificate', '90 calendar days', 'A temporary certificate is issued for up to 120 calendar days.', 4),
  ('reg-transponder-prohibition', 'No, unless operating within 5 miles of an airport', 'Proximity to an airport does not change the rule. Only the Administrator can authorize transponder use.', 4),
  ('reg-visual-observer-comms', 'The crew must use handheld radios on an aviation frequency', 'Any effective means of communication is acceptable. Radios are not mandated.', 4),
  ('reg-vlos-corrective-lenses', 'Corrective lenses, or binoculars when a visual observer is also watching', 'No device other than corrective lenses may be used to satisfy visual line of sight, whoever holds it.', 4),
  ('rid-adsb-cannot-comply', 'Yes, provided a transponder is also installed', 'Neither ADS-B Out nor a transponder can satisfy Remote ID.', 4),
  ('rid-aeronautical-research', 'When the operation is solely for news gathering', '89.101 limits the exception to aeronautical research or showing compliance with regulations.', 4),
  ('rid-broadcast-duration', 'From motor start until the aircraft lands', 'The broadcast must run from takeoff all the way to shutdown, not just until landing.', 4),
  ('rid-broadcast-method', 'Radio broadcast from the control station on behalf of the aircraft', 'The aircraft itself broadcasts the message elements.', 4),
  ('rid-broadcast-module-difference', 'It reports control station location rather than takeoff location, and cannot be used beyond visual line of sight', 'That swaps them. A module reports the takeoff location; standard Remote ID reports the control station.', 4),
  ('rid-fria', 'An area where aircraft without Remote ID may be flown beyond visual line of sight', 'Inside a FRIA, aircraft without Remote ID must stay within visual line of sight.', 4),
  ('rid-fria-eligibility', 'A recognized community-based organization, an educational institution, or a local government', '89.205 makes community-based organizations and educational institutions the only eligible applicants.', 4),
  ('rid-identity-element', 'The serial number of the control station', 'Identity is the aircraft''s serial number or a session ID, not the control station.', 4),
  ('rid-loss-in-flight', 'Land immediately, wherever the aircraft is', 'The rule says as soon as practicable, which allows choosing a safe place to land.', 4),
  ('rid-module-no-emergency-status', 'The altitude of the unmanned aircraft', 'A broadcast module does report aircraft altitude. Emergency status is what it omits.', 4),
  ('rid-preflight-self-test', 'Automatically self-test, and warn the pilot but still allow takeoff if it fails', 'A standard Remote ID aircraft must not be able to take off unless Remote ID is functioning.', 4),
  ('rid-registration-serial', 'The serial number of the remote pilot''s control station', 'The registration must list the broadcast module''s serial number.', 4),
  ('rid-standard-message-elements', 'The position of the aircraft and its takeoff location, velocity, and time mark', 'That is a broadcast module. Standard Remote ID reports control station position and emergency status.', 4),
  ('rid-three-options', 'Standard Remote ID, a broadcast module, or network Remote ID through an approved provider', 'Network Remote ID was dropped from the final rule.', 4),
  ('waiver-application', 'Through the FAA DroneZone, after holding the certificate for 6 months', 'No minimum experience period exists. Applicants show the operation can be done safely.', 4),
  ('waiver-not-waivable', 'The prohibition on operating from a moving vehicle', '107.25 is waivable. Hazardous material under 107.36 is not.', 4),
  ('air-basic-weather-minimums', '3 statute miles visibility, 500 feet below and 1,000 feet horizontally from clouds', 'The horizontal clearance is 2,000 feet.', 4),
  ('air-class-b-shape', 'Dashed magenta lines', 'Dashed magenta marks Class E beginning at the surface.', 4),
  ('air-class-c-depiction', 'A shaded magenta vignette', 'A magenta vignette marks Class E beginning at 700 feet AGL.', 4),
  ('air-class-d-depiction', 'A shaded blue vignette', 'A blue vignette marks Class E beginning at 1,200 feet AGL.', 4),
  ('air-class-e-700', '700 feet MSL', 'The vignette floor is 700 feet above ground level, not mean sea level.', 4),
  ('air-class-e-surface', 'Class D airspace that reverts to Class E when the tower closes', 'Class D is drawn as a dashed blue line. Dashed magenta is Class E to the surface.', 4),
  ('air-class-g-authorization', 'None, unless within 5 statute miles of an airport', 'Part 107 has no 5-mile rule in Class G. You must only avoid interfering with airport traffic.', 4),
  ('air-controlled-firing-area', 'They are charted only on terminal area charts', 'They are not charted at all, because activity stops when aircraft approach.', 4),
  ('air-laanc', 'A request through FAA DroneZone, which is the usual near-real-time route', 'DroneZone requests can take weeks. LAANC is the near-real-time route.', 4),
  ('air-laser-illumination', 'Report it to local police only; the FAA tracks only manned aircraft', 'The FAA asks for reports of all laser illuminations, including of unmanned aircraft.', 4),
  ('air-manned-aircraft-lighting', 'It is crossing from your right to your left', 'Seeing both red and green at once means the aircraft is pointed at you.', 4),
  ('air-moa', 'Airspace where civil flight requires permission from the controlling agency', 'That describes a restricted area. MOAs need no permission, though caution is advised.', 4),
  ('air-mtr-digits', 'The route is flown under IFR at or below 1,500 feet AGL', 'VR means VFR. Four digits mean no segment above 1,500 feet AGL.', 4),
  ('air-notam', 'Permanent information that is already printed on charts', 'NOTAMs carry time-critical information that is not yet charted.', 4),
  ('air-nsa', 'Airspace where flight requires permission from the Department of Homeland Security', 'NSAs request voluntary avoidance. Flight can be temporarily prohibited only by NOTAM.', 4),
  ('air-operations-near-airports', 'No authorization, but you must remain below 200 feet AGL', 'There is no special altitude in Class G near an airport. The rule is not to interfere with traffic.', 4),
  ('air-precipitation-static', 'Static charge that builds on the remote pilot and damages the controller', 'P-static builds on the aircraft as it moves through precipitation.', 4),
  ('air-prohibited-area', 'Airspace where flight is prohibited only while a NOTAM is active', 'That describes a TFR. Prohibited areas are permanent.', 4),
  ('air-restricted-area', 'Restricted areas require ATC authorization through LAANC', 'LAANC does not cover restricted areas. Permission comes from the using or controlling agency.', 4),
  ('air-sUAS-lighting-requirement', 'Anti-collision lighting visible for at least 3 nautical miles', 'The rule says statute miles.', 4),
  ('air-tfr', 'Check B4UFLY once when planning the job', 'TFRs can appear at short notice. Check NOTAMs before every flight, not just at planning.', 4),
  ('air-thermal-plumes', 'They produce strong downdrafts, but only on the downwind side', 'The main hazard is rising, turbulent air directly above them.', 4),
  ('air-trsa', 'An area where radar sequencing is mandatory for all VFR aircraft', 'Participation in a TRSA is voluntary.', 4),
  ('air-uas-facility-map', 'You may fly there up to 100 feet AGL without requesting authorization', 'The number is the most ATC will routinely approve. You still need the authorization.', 4),
  ('air-unlit-ground-hazards', 'Lighted obstruction towers taller than 200 feet AGL', 'Tall towers carry obstruction lights. The hazard is the unlit structures below them.', 4),
  ('air-unmanned-balloons', 'Their radar reflectors interfere with the control link', 'The hazard is the nearly invisible line and payload hanging below.', 4),
  ('air-warning-area', 'Airspace from 12 NM outward from the coast containing hazardous activity', 'Warning areas begin 3 NM from the coast.', 4),
  ('air-wire-environment', 'Wires are highest at mid-span, between the support structures', 'Wires sag. They are lowest at mid-span and highest at the structures.', 4),
  ('load-attachment-security', 'That it is secure and weighs less than 10 percent of the aircraft', 'There is no 10 percent rule. It must be secure and not affect flight characteristics or controllability.', 4),
  ('load-battery-cold', 'Reduced capacity, but improved ability to deliver current under load', 'Cold reduces both capacity and the ability to deliver current.', 4),
  ('load-cg-effect', 'The aircraft becomes more stable but less maneuverable', 'Outside limits, both stability and control margin suffer.', 4),
  ('load-endurance-planning', 'As a reliable figure once 10 percent is subtracted', 'Wind, temperature, payload, and battery age can cut far more than 10 percent.', 4),
  ('load-flight-time-reserve', 'Enough for 30 minutes of additional flight, matching manned VFR day reserves', 'Part 107 sets no reserve. 30 minutes is the manned VFR day rule in 91.151.', 4),
  ('load-max-takeoff-weight', 'That the total is under 55 pounds and the CG is recorded in a log', 'No log is required. The manufacturer''s maximum takeoff weight is the limit that matters here.', 4),
  ('load-performance-data', 'It replaces the need for a preflight assessment', 'Performance data informs the preflight assessment. It does not replace it.', 4),
  ('load-stability-definition', 'The ability to hold an attitude the pilot commands', 'That describes controllability. Stability is the tendency to return after a disturbance.', 4),
  ('load-weight-effect', 'Reduced flight time, but a faster climb from the added momentum', 'Added weight slows the climb.', 4),
  ('load-wind-power-demand', 'It increases only during the climb, then returns to normal', 'Holding position or progress against a headwind demands extra power the whole time.', 4),
  ('wx-advection-fog', 'Moist air moving up a slope and cooling', 'That is upslope fog.', 4),
  ('wx-asos-awos', 'Automated stations that issue forecasts for the next 24 hours', 'They report observations, not forecasts.', 4),
  ('wx-ceiling-definition', 'The height of the lowest scattered, broken, or overcast layer', 'Scattered layers do not form a ceiling.', 4),
  ('wx-cold-front', 'Gradually lowering clouds and steady rain ahead of the front', 'That describes a warm front.', 4),
  ('wx-density-altitude-definition', 'Indicated altitude corrected for non-standard temperature', 'The correction starts from pressure altitude, not indicated altitude.', 4),
  ('wx-density-altitude-effect', 'Reduced lift, but longer flight time because motors draw less current', 'Thin air makes motors work harder and shortens flight time.', 4),
  ('wx-icing-conditions', 'Visible moisture and an air temperature below minus 20 degrees Celsius', 'Icing needs only visible moisture and freezing temperatures. It is most common between 0 and minus 20 degrees Celsius.', 4),
  ('wx-lightning-distance', 'At least 10 nautical miles', 'The guidance is at least 20 nautical miles.', 4),
  ('wx-metar-altimeter', 'An altimeter setting of 299.2 hectopascals', 'The A prefix means inches of mercury. A Q prefix would mean hectopascals.', 4),
  ('wx-metar-cavok-clr', 'Thunderstorms are likely because the spread is small', 'A small spread signals saturation, meaning fog or low cloud, not instability.', 4),
  ('wx-metar-definition', 'A forecast of conditions within 5 statute miles of an airport', 'That is a TAF. A METAR is an observation.', 4),
  ('wx-metar-sky-cover', 'OVC only', 'A broken layer also constitutes a ceiling.', 4),
  ('wx-metar-wind', 'Wind from 210 degrees magnetic at 15 knots, gusting to 25 knots', 'METAR wind direction is referenced to true north, not magnetic.', 4),
  ('wx-microburst', 'A small, intense updraft lasting up to an hour', 'A microburst is a downdraft, usually lasting under 15 minutes.', 4),
  ('wx-radiation-fog', 'Clear skies, strong wind, and high humidity overnight', 'Strong wind mixes the air and lifts it into low stratus instead of fog.', 4),
  ('wx-stable-air', 'Smooth air, cumuliform clouds, and showery precipitation', 'Cumuliform clouds and showers mark unstable air.', 4),
  ('wx-taf-definition', 'A forecast for approximately 5 nautical miles around an airport', 'TAFs cover 5 statute miles.', 4),
  ('wx-thunderstorm-mature-stage', 'The mature stage, marked by the anvil top first appearing', 'The mature stage begins when precipitation falls from the cloud base.', 4),
  ('wx-thunderstorm-stages', 'Towering, mature, anvil', 'The three stages are cumulus, mature, and dissipating.', 4),
  ('wx-unstable-air', 'Turbulence, stratiform clouds, steady precipitation, and good visibility', 'Stratiform clouds and steady precipitation mark stable air.', 4),
  ('wx-weather-briefing-source', 'The METAR alone, since it is an official observation', 'A METAR shows current conditions only. A briefing also needs forecasts and advisories.', 4),
  ('wx-wind-gradient-obstacles', 'It becomes turbulent mostly on the upwind side', 'The rotors and downdrafts form on the downwind side.', 4),
  ('ops-airport-beacon', 'A lighted heliport', 'Heliports flash green, yellow, and white.', 4),
  ('ops-airport-types', 'An airport whose control tower operates part time', 'Airports with a part-time tower are still charted in blue.', 4),
  ('ops-alcohol-8-hours', 'No operation within 8 hours, or at or above 0.08 percent BAC', 'The limit is 0.04 percent.', 4),
  ('ops-atis', 'Weather updated every minute by an automated sensor', 'That describes ASOS or AWOS. ATIS is a recorded broadcast, updated hourly or when things change.', 4),
  ('ops-chart-supplement', 'The UAS Facility Map', 'Facility Maps show authorization altitudes, not runway or frequency data.', 4),
  ('ops-crm-definition', 'Sharing authority equally so no single person is the final authority', 'CRM never removes the remote pilot in command''s final authority.', 4),
  ('ops-ctaf-purpose', 'A frequency on which a ground station sequences arriving traffic', 'No one sequences traffic on CTAF. Pilots self-announce.', 4),
  ('ops-dark-adaptation', 'About 10 minutes', 'Cones adapt in roughly 10 minutes. Full rod adaptation takes about 30.', 4),
  ('ops-dehydration', 'It impairs judgment, but only once you notice thirst', 'Thirst is a late sign. Impairment starts before you feel it.', 4),
  ('ops-emergency-planning', 'Lost link behaviour and a safe landing area, filed with the FAA before flight', 'No filing is required. The plan is for the crew.', 4),
  ('ops-fatigue', 'It degrades attention, but is easy to recognize in yourself', 'Fatigue is hard to self-detect, which is what makes it dangerous.', 4),
  ('ops-frequency-interference', 'GPS multipath reflections off the antennas', 'Multipath degrades position, not the control link.', 4),
  ('ops-gps-loss', 'The aircraft switches to attitude mode and holds its position', 'Attitude mode does not hold position. The aircraft drifts with the wind.', 4),
  ('ops-hazardous-attitude-antiauthority', 'Macho', 'Macho is about proving yourself. Rejecting rules is anti-authority.', 4),
  ('ops-hazardous-attitude-macho', 'Invulnerability', 'Invulnerability is "it won''t happen to me." Showing off for a rival is macho.', 4),
  ('ops-hazardous-attitude-resignation', 'Resignation; the antidote is "Follow the rules. They are usually right"', 'That is the antidote to anti-authority. Resignation''s is "I am not helpless."', 4),
  ('ops-hyperventilation', 'Too little carbon dioxide, corrected by breathing pure oxygen', 'Extra oxygen does not help. Slowing the breathing restores carbon dioxide.', 4),
  ('ops-imsafe', 'The pilot''s fitness and the aircraft''s airworthiness together', 'IMSAFE covers only the pilot. PAVE covers the aircraft.', 4),
  ('ops-lithium-charging', 'Charge on a non-flammable surface with any charger rated for the pack voltage', 'Use the specified charger and stay with it.', 4),
  ('ops-lithium-thermal-runaway', 'Thermal runaway, which stops once the pack is unplugged from the charger', 'Thermal runaway sustains itself. Unplugging does not stop it.', 4),
  ('ops-lithium-transport', 'Protect the terminals and store packs fully charged to prevent cell damage', 'Partial charge is safer for storage and transport.', 4),
  ('ops-lost-link', 'The return-to-home altitude should be set to exactly 400 feet AGL', 'Return-to-home altitude must clear local obstacles. There is no fixed correct value.', 4),
  ('ops-maintenance-records', 'Keep records only for repairs done by the manufacturer', 'Record all maintenance, repairs, and replacements, whoever does them.', 4),
  ('ops-maintenance-who', 'Anyone, provided they hold a remote pilot certificate', 'Part 107 sets no certificate requirement for maintenance.', 4),
  ('ops-mechanical-mitigation', 'Have an FAA repair station inspect the aircraft annually', 'No annual inspection exists. Follow the manufacturer''s maintenance guidance.', 4),
  ('ops-night-vision-off-center', 'Look 30 to 40 degrees off to the side of the object', 'The guidance is 5 to 10 degrees off center.', 4),
  ('ops-otc-medication', 'It is acceptable if you feel no drowsiness after the first dose', 'Impairment can be present without feeling it, and the illness itself matters.', 4),
  ('ops-phonetic-alphabet', 'Kilo Dog Alfa Lima', 'D is Delta. Dog comes from a retired alphabet.', 4),
  ('ops-preflight-inspection', 'Airframe and propellers, battery, and a return-to-home test at full range', 'A full-range RTH test is not part of a preflight inspection.', 4),
  ('ops-preflight-night', 'Verify the anti-collision lighting works and is visible for 1 statute mile', 'The lighting must be visible for 3 statute miles.', 4),
  ('ops-radio-phraseology-altitude', 'An altitude of 2,500 feet above ground level', 'Manned pilots report altitude above mean sea level.', 4),
  ('ops-risk-assessment', 'It removes the need to reassess conditions once on site', 'Conditions change. The advance assessment sets limits; it does not replace looking.', 4),
  ('ops-runway-markings-displaced', 'A displaced threshold usable for taxi only', 'Displaced thresholds are marked with arrows, not chevrons.', 4),
  ('ops-runway-number-heading', 'Approximately 275 to 284 degrees', 'Runway 27 covers about 265 to 274 degrees. 275 to 284 would be runway 28.', 4),
  ('ops-self-announce', 'The aircraft is on downwind, about to turn base for runway 18', 'It is already on base and about to turn final.', 4),
  ('ops-sida', 'An area where visitors must be escorted but staff need no identification', 'Everyone in a SIDA must display identification.', 4),
  ('ops-situational-awareness', 'Listening to the visual observer''s callouts while flying', 'A visual observer''s callouts add awareness. Fixating on a screen removes it.', 4),
  ('ops-situational-awareness', 'Keeping the aircraft close enough to see its orientation', 'Close range helps you keep the aircraft and its orientation in view.', 5),
  ('ops-stress', 'It broadens attention, so more information is processed', 'Acute stress narrows attention.', 4),
  ('ops-task-management', 'Working tasks in checklist order regardless of urgency', 'Task management means prioritizing by urgency, not fixed order.', 4),
  ('ops-team-communication', 'Clear roles, with only the remote pilot allowed to call a stop', 'Anyone on the crew should be empowered to call a stop.', 4),
  ('ops-tower-communication-value', 'To hear the ATIS weather, which only broadcasts on the tower frequency', 'ATIS has its own frequency.', 4),
  ('ops-traffic-pattern-direction', 'Left turns, except at towered airports, where turns are right', 'Standard patterns use left turns at towered and non-towered airports alike.', 4),
  ('ops-unicom', 'A government flight service frequency for weather briefings', 'UNICOM is a non-government station.', 4),
  ('ops-vision-factors', 'Wearing non-polarized sunglasses', 'Sunglasses cut glare and help. Looking toward the sun is the bigger problem.', 4),
  ('ops-vision-factors', 'Flying at dusk with anti-collision lights on', 'Lights make the aircraft easier to see, not harder.', 5),
  ('ops-wildlife-strike', 'Report it to the FAA only if the bird was a protected species', 'The FAA asks for reports of all wildlife strikes.', 4),
  ('ops2-adm-definition', 'A systematic approach used only after an emergency develops', 'ADM applies before and throughout every flight.', 4),
  ('ops2-airport-data-sources', 'Sectional charts alone', 'Charts lack the runway, frequency, and pattern detail in the Chart Supplement.', 4),
  ('ops2-basic-maintenance', 'Scheduled manufacturer maintenance, logged and submitted to the FAA', 'Records are recommended but never submitted to the FAA.', 4),
  ('ops2-battery-failure-inflight', 'Hover in place to conserve power while you assess', 'Hovering still draws heavy power. Land now.', 4),
  ('ops2-controlled-descent', 'Because a forced landing should always be made back at the launch point', 'The launch point may be out of reach. Pick landing areas along the route.', 4),
  ('ops2-decide-model', 'Detect, Evaluate, Choose, Identify, Do, Estimate', 'The order is Detect, Estimate, Choose, Identify, Do, Evaluate.', 4),
  ('ops2-doc-responsibility', 'The owner of the aircraft at the time of registration', 'The person who produces or modifies the aircraft submits it.', 4),
  ('ops2-external-pressure', 'Recognise the pressure, then stretch the limits slightly since the client is waiting', 'Limits set in advance exist precisely so pressure cannot stretch them.', 4),
  ('ops2-firmware', 'Install it on site just before each job so the aircraft is current', 'Never update right before a job. Test new firmware first.', 4),
  ('ops2-flyaway-response', 'Attempt recovery, and file a report with the FAA within 24 hours in every case', 'A report is required only if the flyaway meets the 107.9 thresholds, within 10 days.', 4),
  ('ops2-heatstroke', 'Shivering, slurred speech, and confusion', 'Those are signs of hypothermia.', 4),
  ('ops2-impulsivity', 'Anti-authority', 'Anti-authority is rejecting rules. Acting without thinking is impulsivity.', 4),
  ('ops2-invulnerability', 'Macho', 'Macho is proving yourself. "It only happens to careless people" is invulnerability.', 4),
  ('ops2-lithium-characteristics', 'A high power-to-weight ratio from a non-flammable electrolyte', 'LiPo electrolyte is flammable.', 4),
  ('ops2-lithium-safe-usage', 'Respect minimum voltage, and recharge while still warm to lower resistance', 'Let packs cool before recharging.', 4),
  ('ops2-medication-timing', 'Fly only after a pharmacist confirms the medication is FAA-approved', 'No such approval exists for Part 107 pilots. You judge your own fitness.', 4),
  ('ops2-n-number', 'The aircraft''s model year and serial number', '"Seven two five romeo alpha" is the N-number registration.', 4),
  ('ops2-night-illusions', 'The graveyard spiral', 'That is a vestibular illusion felt inside a manned cockpit.', 4),
  ('ops2-noise-distraction', 'Answer briefly while the aircraft holds a GPS hover', 'Your attention belongs on the aircraft. Let crew handle bystanders.', 4),
  ('ops2-pave-checklist', 'Pilot, Airspace, Visibility, External pressures', 'A and V are Aircraft and enVironment.', 4),
  ('ops2-procedures-at-night', 'Rely on obstacle avoidance sensors to find unlit obstacles', 'Many sensors work poorly in the dark. Survey the site in daylight.', 4),
  ('ops2-procedures-over-people', 'Fly lower so any impact carries less energy', 'Lower does not move people out of the fall zone.', 4),
  ('ops2-propeller-inspection', 'Cracks and chips, which can be sanded smooth before flight', 'Damaged propellers should be replaced, not repaired.', 4),
  ('ops2-record-retention-value', 'They are needed to renew registration every 3 years', 'Registration renewal does not require maintenance records.', 4),
  ('ops2-sectional-chart-purpose', 'Showing the TFRs active during the chart''s effective dates', 'TFRs are issued by NOTAM and are not charted.', 4),
  ('ops2-towered-vs-not', 'Pilots self-separate at a towered field; a controller sequences at a non-towered field', 'That is backwards.', 4),
  ('ops2-vertigo-spatial', 'When the aircraft flies away from the pilot, inputs appear reversed', 'Flying away, inputs match. Facing the pilot, they reverse.', 4),
  ('ops2-visual-observer-value', 'It transfers responsibility for collision avoidance to the observer', 'The remote pilot in command keeps final authority and responsibility.', 4)
) as v(slug, body, rationale, sort_order) on q.slug = v.slug;

insert into ltf.questions (slug, stem, explanation, acs_element_code, difficulty, citation, is_free, is_active) values
  ('reg-falsification', 'A remote pilot changes the completion date on a recurrent training record. What may result?', '107.5 makes any fraudulent or intentionally false record, or an altered certificate or record, grounds to suspend or revoke any certificate, rating, authorization, or waiver the person holds.', 'UA.I.A.K3', 'medium', '14 CFR 107.5', true, true),
  ('reg-records-on-request', 'An FAA inspector asks to see documents you are required to keep under Part 107. What must you do?', '107.7 requires the remote pilot in command, owner, or person at the controls to make the remote pilot certificate and any other document, record, or report required by the regulations available to the Administrator on request.', 'UA.I.A.K7', 'medium', '14 CFR 107.7', true, true),
  ('reg-registration-any-weight', 'You fly a 0.4 pound drone for a paid real estate shoot. Must it be registered?', 'Part 48''s exception for aircraft 0.55 pounds or less applies only to recreational flying. Any aircraft flown under Part 107 must be registered, whatever it weighs.', 'UA.I.B.K1', 'hard', '14 CFR 48.15', true, true),
  ('reg-registration-marking', 'Where must the FAA registration number be displayed on a small unmanned aircraft?', 'Since February 2019 the registration number must be legible on an external surface of the aircraft. Inside a battery compartment no longer satisfies the rule.', 'UA.I.B.K1', 'medium', '14 CFR 48.205', true, true),
  ('reg-condition-for-safe-operation', 'Who must check that the small UAS is in a condition for safe operation before each flight?', '107.15 makes the remote pilot in command responsible for checking the system before each flight, and prohibits operating it when it is not safe.', 'UA.I.B.K2', 'easy', '14 CFR 107.15', true, true),
  ('reg-careless-reckless', 'A remote pilot makes low passes over a crowded beach to impress friends. Which rule is most directly violated?', '107.23(a) prohibits operating a small UAS in a careless or reckless manner so as to endanger the life or property of another.', 'UA.I.B.K6a', 'easy', '14 CFR 107.23', true, true),
  ('reg-alcohol-timing', 'You had one beer at 10 p.m. Your shoot launches at 7 a.m. the next morning. May you act as a crew member?', 'Part 107 applies 91.17: no acting as a crew member within 8 hours of drinking, or with a blood alcohol concentration of 0.04 percent or more. Both conditions must be met; 9 hours have passed, so you may fly if you are below 0.04.', 'UA.I.B.K8', 'medium', '14 CFR 107.27; 14 CFR 91.17', true, true),
  ('reg-night-requirements', 'What does a remote pilot need to fly at night under Part 107 today?', 'Since April 2021, 107.29 allows night operations without a waiver if the pilot has passed the updated knowledge test or completed the updated training, and the aircraft has anti-collision lighting visible for 3 statute miles.', 'UA.I.B.K9', 'medium', '14 CFR 107.29', true, true),
  ('reg-property-for-hire', 'A client wants to pay you to deliver a package by drone. Which condition applies under Part 107?', 'Part 107 allows carrying property for compensation if the total weight with cargo is under 55 pounds, the flight stays within visual line of sight, it is not from a moving vehicle, and it stays within one state.', 'UA.I.B.K26', 'hard', 'AC 107-2A; 14 CFR 107.3', true, true),
  ('reg-automated-flight', 'Your aircraft flies a preprogrammed mapping mission on autopilot. What does Part 107 require of you?', 'Automated flight is allowed under Part 107, but the remote pilot in command must be able to intervene and change the flight path, and visual line of sight must still be maintained.', 'UA.I.B.K23', 'medium', '14 CFR 107.19; 14 CFR 107.31', true, true),
  ('reg-tfr-overrides-laanc', 'You hold a LAANC authorization for a job site. A VIP TFR is then issued covering it. What applies?', '107.47 requires compliance with flight restrictions designated by NOTAM. A LAANC authorization grants controlled airspace access; it does not override a TFR.', 'UA.I.B.K19', 'hard', '14 CFR 107.47; 14 CFR 91.141', true, true),
  ('reg-airport-interference', 'What does 107.43 prohibit near airports?', '107.43 prohibits operating a small UAS in a way that interferes with operations and traffic patterns at any airport, heliport, or seaplane base.', 'UA.I.B.K17', 'medium', '14 CFR 107.43', true, true),
  ('reg-right-of-way-passing', 'Besides yielding right of way, what does 107.37 require around other aircraft?', '107.37 requires the small UAS to yield to all aircraft and not pass over, under, or ahead of one unless well clear.', 'UA.I.B.K14a', 'medium', '14 CFR 107.37', true, true),
  ('reg-certificate-requirements', 'Which of the following is required to obtain a remote pilot certificate?', 'An applicant must be at least 16, read, speak, write and understand English, be in a condition to fly safely, pass the initial knowledge test, and clear TSA security vetting. There is no flight test and no medical certificate.', 'UA.I.B.K22', 'easy', '14 CFR 107.61', true, true),
  ('oop-night-over-people', 'What additional equipment requirement applies to operations over people at night?', 'Operations over people at night are allowed under the categories, but the aircraft must have lit anti-collision lighting visible for at least 3 statute miles, and the pilot must meet the updated night training or test.', 'UA.I.E.K2', 'hard', '14 CFR 107.29', true, true),
  ('oop-kinetic-energy-measure', 'How does Part 107 express the Category 2 injury threshold?', 'Category 2 aircraft must not cause injury equal to or greater than the severity caused by a rigid object transferring 11 foot-pounds of kinetic energy on impact.', 'UA.I.E.K16', 'hard', '14 CFR 107.120', true, true),
  ('oop-no-fixed-distance', 'What minimum lateral distance from a non-participating person does Part 107 set for Category 2 operations?', 'Subpart D sets no fixed distance. Eligibility over people comes from the aircraft''s category and its operating limits, not a set buffer.', 'UA.I.E.K5', 'hard', '14 CFR 107 Subpart D', true, true),
  ('oop-operating-instructions', 'What must the producer of a Category 2 or 3 aircraft make available to its owner?', 'Producers must provide remote pilot operating instructions describing how to operate the aircraft within its eligibility, alongside the declaration of compliance and label.', 'UA.I.E.K9', 'hard', '14 CFR 107.125', true, true),
  ('air-who-authorizes', 'Who issues authorizations to fly in Class B, C, D, or surface Class E airspace under Part 107?', 'Authorization comes from air traffic control, usually through LAANC, or through FAA DroneZone where LAANC is not available.', 'UA.II.A.K4', 'easy', '14 CFR 107.41', true, true),
  ('air-accident-causes', 'What most often contributes to aircraft accidents, including small UAS mishaps?', 'Across aviation, most accidents trace to human factors: decisions, procedures, and attention, rather than mechanical failure alone.', 'UA.II.B.K4a', 'medium', 'FAA-H-8083-25; FAA-H-8083-2', true, true),
  ('air-obstacle-agl', 'On a sectional chart, an obstruction shows 1549 in bold with (349) beneath it. What does 349 indicate?', 'The bold number is the top of the obstruction in feet MSL. The number in parentheses is its height above ground level.', 'UA.II.B.K7', 'medium', 'FAA Aeronautical Chart User''s Guide', true, true),
  ('air-night-equipment', 'What personal equipment helps a remote pilot during a night operation?', 'A dimmable or red flashlight lets you read checklists and handle equipment while preserving night vision, which takes about 30 minutes to rebuild.', 'UA.II.B.K6', 'medium', 'FAA-H-8083-25', true, true),
  ('wx-tornadoes', 'Tornadoes are most often associated with what kind of weather?', 'Most strong tornadoes come from severe thunderstorms, particularly rotating supercells.', 'UA.III.B.K1f', 'easy', 'FAA-H-8083-28', true, true),
  ('wx-hail-outside', 'Where can hail be encountered relative to a thunderstorm?', 'Hail can fall from the anvil into clear air miles from the storm core, so clear air near a storm is not safe.', 'UA.III.B.K1h', 'medium', 'FAA-H-8083-28', true, true),
  ('wx-surface-analysis', 'What does a surface analysis chart show?', 'A surface analysis shows observed fronts, high and low pressure centers, isobars, and station data at the chart time.', 'UA.III.A.K4', 'medium', 'FAA-H-8083-28', true, true),
  ('wx-prog-chart', 'What is a short-range surface prognostic chart used for?', 'Prog charts forecast where fronts, pressure systems, and precipitation will be at set times ahead.', 'UA.III.A.K4', 'medium', 'FAA-H-8083-28', true, true),
  ('wx-heat-performance', 'How does a hot day affect a multirotor''s performance?', 'Hot air is less dense, so propellers make less thrust per revolution. Motors and the battery work harder, and flight time drops.', 'UA.III.B.K1', 'medium', 'FAA-H-8083-25', true, true),
  ('wx-dewpoint-spread', 'A METAR shows 18/06. What is the temperature-dewpoint spread, and what does it suggest?', '18 minus 6 is a 12 degree Celsius spread. The air is far from saturation, so fog is unlikely.', 'UA.III.B.K1i', 'medium', 'FAA-H-8083-28', true, true),
  ('wx-metar-visibility', 'In a METAR, what does 1/2SM FG report?', 'SM is statute miles and FG is fog. Visibility is one-half statute mile in fog.', 'UA.III.A.K2', 'easy', 'AIM 7-1; FAA-H-8083-28', true, true),
  ('wx-metar-ceiling-height', 'In a METAR, what does BKN008 report?', 'Cloud heights are reported in hundreds of feet AGL. BKN008 is a broken layer at 800 feet AGL, which forms a ceiling.', 'UA.III.A.K2', 'medium', 'AIM 7-1; FAA-H-8083-28', true, true),
  ('wx-taf-fm', 'In a TAF, what does FM1600 mean?', 'FM marks a rapid and lasting change. FM1600 means from 1600 UTC, the conditions that follow apply.', 'UA.III.A.K3', 'medium', 'AIM 7-1; FAA-H-8083-28', true, true),
  ('wx-taf-prob', 'What does PROB30 mean in a TAF?', 'PROB30 gives a 30 percent probability of the thunderstorms or precipitation that follow during the stated period.', 'UA.III.A.K3', 'medium', 'AIM 7-1; FAA-H-8083-28', true, true),
  ('wx-warm-front', 'What weather is typical ahead of an approaching warm front?', 'Warm fronts slope gently. Clouds lower gradually and steady precipitation falls over a wide area ahead of the front, often with poor visibility.', 'UA.III.B.K1d', 'medium', 'FAA-H-8083-28', true, true),
  ('wx-inversion', 'What is a temperature inversion, and what does it often produce near the ground?', 'In an inversion, temperature rises with height. The stable layer traps smoke, haze, and moisture, often reducing visibility.', 'UA.III.B.K1c', 'medium', 'FAA-H-8083-28', true, true),
  ('wx-ridge-wind', 'Wind blows steadily across a ridge. What should you expect on the downwind (lee) side?', 'Air rises on the windward side and sinks with turbulence on the lee side.', 'UA.III.B.K1b', 'medium', 'FAA-H-8083-28', true, true),
  ('load-bank-load-factor', 'What happens to load factor as bank angle increases in a level turn?', 'Load factor rises with bank angle, slowly at first and then steeply past about 45 degrees. The structure and motors carry more load.', 'UA.IV.A.K1a', 'medium', 'FAA-H-8083-25', true, true),
  ('load-60-degree-bank', 'In a level 60 degree bank, what is the load factor?', 'Load factor in a level turn is 1 divided by the cosine of the bank angle. At 60 degrees it is 2 G.', 'UA.IV.A.K1a', 'medium', 'FAA-H-8083-25', true, true),
  ('load-offset-payload', 'A camera is mounted off center on a multirotor. What is the likely effect?', 'An off-center load moves the CG. Some motors must work harder to hold level, reducing endurance and leaving less control margin.', 'UA.IV.A.K1b', 'medium', 'FAA-H-8083-25', true, true),
  ('load-high-elevation', 'You launch from a site at 7,000 feet MSL. Compared with sea level, what should you expect?', 'Air at 7,000 feet is much less dense. Propellers produce less thrust per revolution, motors work harder, and flight time drops.', 'UA.IV.A.K2', 'medium', 'FAA-H-8083-25', true, true),
  ('load-voltage-sag', 'Why can a battery reading 30 percent trigger a low-voltage landing during a hard climb?', 'Voltage sags under heavy current draw. The aircraft can read the sag as a depleted battery and force a landing.', 'UA.IV.A.K2', 'hard', 'FAA-H-8083-25', true, true),
  ('load-wind-limit', 'The manufacturer rates the aircraft for 24 mph wind. Winds are 20 gusting 30 mph. What is the sound decision?', 'Gusts are what the aircraft has to survive. With gusts above the rated limit, don''t fly.', 'UA.IV.A.K2', 'medium', 'FAA-H-8083-2', true, true),
  ('load-damaged-prop', 'How does a nicked propeller affect performance?', 'Damage reduces thrust efficiency and adds vibration that can upset the flight controller''s sensors.', 'UA.IV.A.K2', 'easy', 'FAA-H-8083-25', true, true),
  ('ops-ctaf-inbound-call', 'You hear "Rockwall traffic, Cessna three four tango, five miles south, inbound for landing runway one seven." Where should you look?', 'The aircraft is 5 miles south and heading toward the airport to land on runway 17.', 'UA.V.A.K3', 'medium', 'AIM 4-1-9', true, true),
  ('ops-wind-sock', 'An airport wind sock is fully extended. What wind speed does that suggest?', 'A standard wind cone is fully extended at about 15 knots or more.', 'UA.V.B.K3', 'easy', 'AIM 2-3-14; FAA-H-8083-25', true, true),
  ('ops-pattern-legs', 'In order after takeoff, what are the legs of a standard traffic pattern?', 'Departure or upwind, crosswind, downwind, base, then final.', 'UA.V.B.K4', 'medium', 'AIM 4-3-2', true, true),
  ('ops-macho-antidote', 'What is the antidote to the macho hazardous attitude?', 'Each hazardous attitude has an antidote. For macho it is "Taking chances is foolish."', 'UA.V.D.K4', 'easy', 'FAA-H-8083-2', true, true),
  ('ops-imsafe-s', 'In the IMSAFE checklist, what does the S stand for?', 'IMSAFE is Illness, Medication, Stress, Alcohol, Fatigue, and Emotion.', 'UA.V.E.K7', 'easy', 'FAA-H-8083-25', true, true),
  ('ops-swollen-lipo', 'A LiPo pack is noticeably swollen after a flight. What should you do?', 'Swelling means internal damage and gas buildup. Retire the pack and dispose of it through a battery recycler.', 'UA.V.C.K2c', 'easy', 'FAA-H-8083-25; manufacturer guidance', true, true),
  ('ops-rth-tree-line', 'Return-to-home altitude is set to 80 feet. A 120 foot tree line stands between you and the aircraft. What happens on a lost link?', 'Return-to-home climbs only to the set altitude, then flies straight back. At 80 feet it can fly into a 120 foot tree line.', 'UA.V.C.K3', 'medium', 'FAA-H-8083-2; manufacturer guidance', true, true),
  ('ops-3p-model', 'What does the 3P model for managing risk stand for?', 'Perceive the hazards, Process them by evaluating risk, and Perform by acting to reduce it.', 'UA.V.D.K1', 'medium', 'FAA-H-8083-2', true, true),
  ('ops-crew-briefing', 'What should a preflight crew briefing cover?', 'Brief roles, the flight plan, emergency procedures, and agreed calls so everyone knows what to do before something goes wrong.', 'UA.V.D.K1a', 'easy', 'FAA-H-8083-2', true, true),
  ('ops-compass-calibration', 'Why calibrate a drone''s compass away from vehicles and steel structures?', 'Nearby steel distorts the local magnetic field, so calibration there bakes in a wrong heading.', 'UA.V.C.K4', 'medium', 'Manufacturer guidance', true, true);

insert into ltf.choices (question_id, label, body, is_correct, rationale, sort_order, tier)
select q.id, v.label, v.body, v.is_correct, v.rationale, v.sort_order, v.tier
from ltf.questions q join (values
  ('reg-falsification', 'A', 'Suspension or revocation of any certificate, authorization, or waiver they hold', true, null, 1, null::smallint),
  ('reg-falsification', 'B', 'Nothing, because training records are never checked', false, 'Altering a record is itself a violation, checked or not.', 2, 1),
  ('reg-falsification', 'C', 'A warning letter only, since no flight took place', false, 'No flight is needed. The falsified record is the violation.', 3, 2),
  ('reg-falsification', 'D', 'Revocation of the remote pilot certificate only, leaving any waivers intact', false, '107.5 reaches any certificate, rating, authorization, or waiver held.', 4, 3),
  ('reg-records-on-request', 'A', 'Make the required documents and records available on request', true, null, 1, null::smallint),
  ('reg-records-on-request', 'B', 'Nothing; Part 107 operators keep no records the FAA can ask for', false, '107.7 expressly covers records and reports required by the regulations.', 2, 1),
  ('reg-records-on-request', 'C', 'Mail them to the nearest FSDO within 30 days', false, 'The obligation is to make them available on request, not to mail them within a set window.', 3, 2),
  ('reg-records-on-request', 'D', 'Make them available only if a safety event has been reported', false, 'The duty applies on any request, not only after a reported event.', 4, 3),
  ('reg-registration-any-weight', 'A', 'Yes; every aircraft flown under Part 107 must be registered, whatever it weighs', true, null, 1, null::smallint),
  ('reg-registration-any-weight', 'B', 'Only if it will be flown above 400 feet AGL', false, 'Altitude has nothing to do with registration.', 2, 1),
  ('reg-registration-any-weight', 'C', 'No; registration begins at 0.55 pounds', false, 'That threshold applies only to recreational flying.', 3, 2),
  ('reg-registration-any-weight', 'D', 'Yes, though the owner''s recreational registration number covers it', false, 'Part 107 aircraft are registered individually. A recreational registration covers only recreational flying.', 4, 3),
  ('reg-registration-marking', 'A', 'On an external surface of the aircraft', true, null, 1, null::smallint),
  ('reg-registration-marking', 'B', 'On the remote pilot certificate', false, 'The certificate is the pilot''s, not the aircraft''s marking.', 2, 1),
  ('reg-registration-marking', 'C', 'Inside the battery compartment, if it opens without tools', false, 'That was allowed before 2019. It must now be on an external surface.', 3, 2),
  ('reg-registration-marking', 'D', 'On the controller, so it can be shown to law enforcement', false, 'The number goes on the aircraft itself.', 4, 3),
  ('reg-condition-for-safe-operation', 'A', 'The remote pilot in command', true, null, 1, null::smallint),
  ('reg-condition-for-safe-operation', 'B', 'The FAA, through an annual inspection', false, 'There is no FAA annual inspection for a small UAS.', 2, 1),
  ('reg-condition-for-safe-operation', 'C', 'An FAA-certificated airframe and powerplant mechanic', false, 'Part 107 requires no certificated mechanic.', 3, 2),
  ('reg-condition-for-safe-operation', 'D', 'The person at the controls, if that person is not the rPIC', false, '107.15 puts the duty on the remote pilot in command.', 4, 3),
  ('reg-careless-reckless', 'A', 'Operating carelessly or recklessly so as to endanger life or property', true, null, 1, null::smallint),
  ('reg-careless-reckless', 'B', 'Failing to file a flight plan', false, 'Part 107 has no flight plan requirement.', 2, 1),
  ('reg-careless-reckless', 'C', 'The 400 foot altitude limit', false, 'Low passes do not break the altitude limit.', 3, 2),
  ('reg-careless-reckless', 'D', 'The prohibition on sustained flight over moving vehicles', false, 'A beach crowd is not moving vehicles. The conduct itself is careless or reckless.', 4, 3),
  ('reg-alcohol-timing', 'A', 'Yes, provided your blood alcohol concentration is below 0.04 percent', true, null, 1, null::smallint),
  ('reg-alcohol-timing', 'B', 'Yes, because Part 107 has no alcohol rules', false, '107.27 applies the 91.17 alcohol rules to Part 107 crew.', 2, 1),
  ('reg-alcohol-timing', 'C', 'No; Part 107 requires 24 hours between drinking and flying', false, 'The bottle to throttle rule is 8 hours.', 3, 2),
  ('reg-alcohol-timing', 'D', 'Yes, because 8 hours have passed, whatever your blood alcohol level', false, 'Both conditions apply: 8 hours and under 0.04 percent.', 4, 3),
  ('reg-night-requirements', 'A', 'The updated knowledge test or training, plus anti-collision lighting visible for 3 statute miles', true, null, 1, null::smallint),
  ('reg-night-requirements', 'B', 'A visual observer for every 15 minutes of flight', false, 'No such requirement exists.', 2, 1),
  ('reg-night-requirements', 'C', 'A night waiver issued under 107.200', false, 'That was the rule before April 2021.', 3, 2),
  ('reg-night-requirements', 'D', 'The updated test or training, plus anti-collision lighting visible for 1 statute mile', false, 'The lighting must be visible for 3 statute miles.', 4, 3),
  ('reg-property-for-hire', 'A', 'The aircraft and package must weigh under 55 pounds total, and the flight must stay within one state', true, null, 1, null::smallint),
  ('reg-property-for-hire', 'B', 'The package must be insured by the FAA', false, 'The FAA does not insure cargo.', 2, 1),
  ('reg-property-for-hire', 'C', 'Property may never be carried for pay under Part 107', false, 'Limited carriage for hire is allowed.', 3, 2),
  ('reg-property-for-hire', 'D', 'The flight may cross a state line if it stays within visual line of sight', false, 'Carriage for hire must stay within a single state.', 4, 3),
  ('reg-automated-flight', 'A', 'Be able to intervene at any time and keep the aircraft in visual line of sight', true, null, 1, null::smallint),
  ('reg-automated-flight', 'B', 'Nothing; automated flights are exempt from Part 107', false, 'Automation does not change who is responsible.', 2, 1),
  ('reg-automated-flight', 'C', 'A waiver, since automated flight is not permitted', false, 'Automated flight is permitted without a waiver.', 3, 2),
  ('reg-automated-flight', 'D', 'Keep visual line of sight through the live camera feed while automation flies', false, 'A camera feed never satisfies visual line of sight.', 4, 3),
  ('reg-tfr-overrides-laanc', 'A', 'The TFR applies; the LAANC authorization does not override it', true, null, 1, null::smallint),
  ('reg-tfr-overrides-laanc', 'B', 'TFRs apply only to manned aircraft', false, 'TFRs apply to unmanned aircraft too.', 2, 1),
  ('reg-tfr-overrides-laanc', 'C', 'You may fly if you stay below 200 feet AGL', false, 'A TFR has no low-altitude exception for drones.', 3, 2),
  ('reg-tfr-overrides-laanc', 'D', 'You may fly if you phone the issuing facility before launch', false, 'Notifying someone is not authorization. Fly only under the TFR''s stated conditions.', 4, 3),
  ('reg-airport-interference', 'A', 'Interfering with operations and traffic patterns at any airport, heliport, or seaplane base', true, null, 1, null::smallint),
  ('reg-airport-interference', 'B', 'Photographing aircraft parked on the ramp', false, 'Photography is not the issue. Interference is.', 2, 1),
  ('reg-airport-interference', 'C', 'Any flight within 5 statute miles of an airport without notifying the operator', false, 'Part 107 has no 5-mile notification rule.', 3, 2),
  ('reg-airport-interference', 'D', 'Interfering with traffic patterns at towered airports only', false, 'The rule covers every airport, heliport, and seaplane base.', 4, 3),
  ('reg-right-of-way-passing', 'A', 'Do not pass over, under, or ahead of another aircraft unless well clear', true, null, 1, null::smallint),
  ('reg-right-of-way-passing', 'B', 'Announce position on CTAF before every flight', false, 'Part 107 pilots are not required to transmit.', 2, 1),
  ('reg-right-of-way-passing', 'C', 'Climb above manned traffic to stay clear', false, 'Climbing toward traffic is the opposite of yielding.', 3, 2),
  ('reg-right-of-way-passing', 'D', 'Passing directly beneath manned aircraft is always permitted', false, 'Passing under is prohibited unless well clear.', 4, 3),
  ('reg-certificate-requirements', 'A', 'Pass the initial knowledge test and clear TSA security vetting', true, null, 1, null::smallint),
  ('reg-certificate-requirements', 'B', 'Log 40 hours of flight time with an instructor', false, 'No flight time is required.', 2, 1),
  ('reg-certificate-requirements', 'C', 'Hold a third-class medical certificate', false, 'No medical certificate is required.', 3, 2),
  ('reg-certificate-requirements', 'D', 'Pass a practical flight test with an FAA examiner', false, 'There is no practical test for the remote pilot certificate.', 4, 3),
  ('oop-night-over-people', 'A', 'Lit anti-collision lighting visible for at least 3 statute miles', true, null, 1, null::smallint),
  ('oop-night-over-people', 'B', 'Each person below must carry a flashlight', false, 'No such requirement exists.', 2, 1),
  ('oop-night-over-people', 'C', 'A waiver is always required', false, 'Night operations over people need no waiver if the requirements are met.', 3, 2),
  ('oop-night-over-people', 'D', 'Night operations over people are limited to Category 1 aircraft', false, 'Any eligible category may operate over people at night with proper lighting.', 4, 3),
  ('oop-kinetic-energy-measure', 'A', 'Injury severity equal to a rigid object transferring 11 foot-pounds on impact', true, null, 1, null::smallint),
  ('oop-kinetic-energy-measure', 'B', 'The propeller noise level at 50 feet', false, 'Noise is not part of the standard.', 2, 1),
  ('oop-kinetic-energy-measure', 'C', 'The aircraft''s top speed, regardless of its weight', false, 'Kinetic energy depends on both mass and speed.', 3, 2),
  ('oop-kinetic-energy-measure', 'D', 'Injury severity equal to a rigid object transferring 25 foot-pounds on impact', false, '25 foot-pounds is the Category 3 threshold.', 4, 3),
  ('oop-no-fixed-distance', 'A', 'None; eligibility comes from the aircraft''s category, not a set distance', true, null, 1, null::smallint),
  ('oop-no-fixed-distance', 'B', '1 statute mile', false, 'No such distance appears in the rule.', 2, 1),
  ('oop-no-fixed-distance', 'C', '25 feet', false, 'Part 107 sets no fixed lateral distance.', 3, 2),
  ('oop-no-fixed-distance', 'D', 'None while passing over, but 50 feet when hovering', false, 'The rule draws no distinction by distance.', 4, 3),
  ('oop-operating-instructions', 'A', 'Remote pilot operating instructions for operating within the aircraft''s eligibility', true, null, 1, null::smallint),
  ('oop-operating-instructions', 'B', 'A free remote pilot certificate', false, 'Producers cannot issue pilot certificates.', 2, 1),
  ('oop-operating-instructions', 'C', 'A signed waiver for flight over open-air assemblies', false, 'Producers cannot issue waivers.', 3, 2),
  ('oop-operating-instructions', 'D', 'The FAA''s acceptance letter, which must be carried in flight', false, 'There is no requirement to carry an acceptance letter.', 4, 3),
  ('air-who-authorizes', 'A', 'Air traffic control, through LAANC or FAA DroneZone', true, null, 1, null::smallint),
  ('air-who-authorizes', 'B', 'The local police department', false, 'Police do not control airspace.', 2, 1),
  ('air-who-authorizes', 'C', 'The airport manager', false, 'The airport manager does not authorize controlled airspace access.', 3, 2),
  ('air-who-authorizes', 'D', 'Flight Service, as part of a weather briefing', false, 'Flight Service briefs; it does not authorize airspace access.', 4, 3),
  ('air-accident-causes', 'A', 'Human factors such as decisions and procedures, more than mechanical failure', true, null, 1, null::smallint),
  ('air-accident-causes', 'B', 'Bird attacks on every flight', false, 'Wildlife strikes happen but are not the leading cause.', 2, 1),
  ('air-accident-causes', 'C', 'Manufacturing defects', false, 'Defects occur, but human factors dominate.', 3, 2),
  ('air-accident-causes', 'D', 'GPS loss from solar activity', false, 'Solar activity is a rare cause.', 4, 3),
  ('air-obstacle-agl', 'A', 'Its height above ground level, in feet', true, null, 1, null::smallint),
  ('air-obstacle-agl', 'B', 'Its radio frequency', false, 'Obstructions do not carry frequencies.', 2, 1),
  ('air-obstacle-agl', 'C', 'Its height above mean sea level, in feet', false, 'The bold figure is MSL. Parentheses show AGL.', 3, 2),
  ('air-obstacle-agl', 'D', 'Its height above the nearest runway, in feet', false, 'Chart heights are AGL or MSL, never relative to a runway.', 4, 3),
  ('air-night-equipment', 'A', 'A flashlight with a red or dimmable setting', true, null, 1, null::smallint),
  ('air-night-equipment', 'B', 'Sunglasses to cut glare', false, 'Sunglasses reduce what little light there is.', 2, 1),
  ('air-night-equipment', 'C', 'A bright white headlamp worn throughout', false, 'Bright white light destroys dark adaptation.', 3, 2),
  ('air-night-equipment', 'D', 'A flashlight with a blue filter', false, 'Red preserves night vision. Blue light hurts it.', 4, 3),
  ('wx-tornadoes', 'A', 'Severe thunderstorms, especially supercells', true, null, 1, null::smallint),
  ('wx-tornadoes', 'B', 'Radiation fog', false, 'Fog forms in calm, stable air.', 2, 1),
  ('wx-tornadoes', 'C', 'Warm fronts with steady drizzle', false, 'Steady drizzle marks stable air, not tornadoes.', 3, 2),
  ('wx-tornadoes', 'D', 'Short-lived air mass thunderstorms on calm summer afternoons', false, 'Air mass storms rarely produce tornadoes.', 4, 3),
  ('wx-hail-outside', 'A', 'In clear air beneath the anvil, miles from the storm core', true, null, 1, null::smallint),
  ('wx-hail-outside', 'B', 'Only on the ground after the storm passes', false, 'Hail falls through the air during the storm.', 2, 1),
  ('wx-hail-outside', 'C', 'Only inside the cloud', false, 'Hail can fall well outside the cloud.', 3, 2),
  ('wx-hail-outside', 'D', 'Only during the dissipating stage', false, 'Hail is most likely in the mature stage.', 4, 3),
  ('wx-surface-analysis', 'A', 'Observed fronts, pressure systems, and station data at a point in time', true, null, 1, null::smallint),
  ('wx-surface-analysis', 'B', 'Restricted areas and MOAs', false, 'Those are on aeronautical charts.', 2, 1),
  ('wx-surface-analysis', 'C', 'Forecast cloud tops for the next 24 hours', false, 'The analysis shows observations, not forecasts.', 3, 2),
  ('wx-surface-analysis', 'D', 'Forecast frontal positions 12 hours ahead', false, 'That is a prognostic chart.', 4, 3),
  ('wx-prog-chart', 'A', 'Seeing forecast positions of fronts, pressure systems, and precipitation', true, null, 1, null::smallint),
  ('wx-prog-chart', 'B', 'Finding airport frequencies', false, 'Frequencies are in the Chart Supplement.', 2, 1),
  ('wx-prog-chart', 'C', 'Reading current observed conditions at airports', false, 'Current observations are METARs.', 3, 2),
  ('wx-prog-chart', 'D', 'Seeing radar returns from the past hour', false, 'That is a radar product, not a prog chart.', 4, 3),
  ('wx-heat-performance', 'A', 'Less lift per revolution, harder working motors, and shorter flight time', true, null, 1, null::smallint),
  ('wx-heat-performance', 'B', 'Heat improves battery chemistry and lengthens flight', false, 'Heat stresses the battery and thin air shortens flight.', 2, 1),
  ('wx-heat-performance', 'C', 'No effect below 400 feet AGL', false, 'Density changes with temperature at any height.', 3, 2),
  ('wx-heat-performance', 'D', 'Less lift, but the battery delivers more energy, so flight time is unchanged', false, 'Flight time drops on hot days.', 4, 3),
  ('wx-dewpoint-spread', 'A', '12 degrees Celsius; fog is unlikely', true, null, 1, null::smallint),
  ('wx-dewpoint-spread', 'B', '24 degrees Celsius; fog is certain', false, 'The spread is the difference, not the sum.', 2, 1),
  ('wx-dewpoint-spread', 'C', '12 degrees Celsius; fog is likely soon', false, 'A wide spread means the air is dry.', 3, 2),
  ('wx-dewpoint-spread', 'D', '6 degrees Celsius; fog is likely', false, '06 is the dewpoint, not the spread.', 4, 3),
  ('wx-metar-visibility', 'A', 'Visibility one-half statute mile in fog', true, null, 1, null::smallint),
  ('wx-metar-visibility', 'B', 'Half the sky covered by fog', false, 'Sky cover is reported in a separate group.', 2, 1),
  ('wx-metar-visibility', 'C', 'Visibility one-half statute mile in haze', false, 'Haze is HZ. FG is fog.', 3, 2),
  ('wx-metar-visibility', 'D', 'Visibility one-half nautical mile in fog', false, 'U.S. METAR visibility is in statute miles.', 4, 3),
  ('wx-metar-ceiling-height', 'A', 'A broken layer at 800 feet AGL, forming a ceiling', true, null, 1, null::smallint),
  ('wx-metar-ceiling-height', 'B', 'A broken layer at 8 feet', false, 'Heights are in hundreds of feet.', 2, 1),
  ('wx-metar-ceiling-height', 'C', 'A broken layer at 8,000 feet AGL', false, '008 means 800 feet, not 8,000.', 3, 2),
  ('wx-metar-ceiling-height', 'D', 'A broken layer at 800 feet MSL', false, 'METAR cloud heights are above ground level.', 4, 3),
  ('wx-taf-fm', 'A', 'From 1600 UTC, a lasting change to the conditions that follow', true, null, 1, null::smallint),
  ('wx-taf-fm', 'B', 'A frequency of 16.00 MHz', false, 'TAFs do not carry frequencies.', 2, 1),
  ('wx-taf-fm', 'C', 'From 1600 local time', false, 'TAF times are UTC.', 3, 2),
  ('wx-taf-fm', 'D', 'Temporary fluctuations beginning at 1600 UTC', false, 'That is TEMPO. FM is a lasting change.', 4, 3),
  ('wx-taf-prob', 'A', 'A 30 percent probability of the conditions that follow', true, null, 1, null::smallint),
  ('wx-taf-prob', 'B', 'Visibility of 30 statute miles', false, 'Visibility is reported separately.', 2, 1),
  ('wx-taf-prob', 'C', 'A 30 percent chance of rain, and nothing else', false, 'It applies to whatever conditions follow.', 3, 2),
  ('wx-taf-prob', 'D', 'A 30 percent probability, valid for the next 30 minutes', false, 'The period comes from the time group, not the number 30.', 4, 3),
  ('wx-warm-front', 'A', 'Gradually lowering stratiform clouds and steady precipitation over a wide area', true, null, 1, null::smallint),
  ('wx-warm-front', 'B', 'Clear skies and unlimited visibility', false, 'Warm fronts bring cloud and precipitation.', 2, 1),
  ('wx-warm-front', 'C', 'A narrow line of thunderstorms with gusty wind', false, 'That describes a cold front.', 3, 2),
  ('wx-warm-front', 'D', 'Lowering cumuliform clouds with showers in a narrow band', false, 'Warm fronts produce stratiform cloud over a wide area.', 4, 3),
  ('wx-inversion', 'A', 'Temperature rising with height, trapping haze and smoke and reducing visibility', true, null, 1, null::smallint),
  ('wx-inversion', 'B', 'Temperature dropping 10 degrees per 100 feet', false, 'That is not an inversion.', 2, 1),
  ('wx-inversion', 'C', 'Temperature rising with height, producing strong thermals', false, 'Inversions are stable and suppress thermals.', 3, 2),
  ('wx-inversion', 'D', 'Temperature falling faster than standard with height, trapping haze', false, 'Falling faster than standard is unstable air.', 4, 3),
  ('wx-ridge-wind', 'A', 'Downdrafts and turbulence', true, null, 1, null::smallint),
  ('wx-ridge-wind', 'B', 'Calm air ideal for hovering', false, 'The lee side is turbulent.', 2, 1),
  ('wx-ridge-wind', 'C', 'Steady updrafts', false, 'Updrafts are on the windward side.', 3, 2),
  ('wx-ridge-wind', 'D', 'Updrafts on the lee side, downdrafts on the windward side', false, 'That is backwards.', 4, 3),
  ('load-bank-load-factor', 'A', 'It increases, so the structure and motors carry more load', true, null, 1, null::smallint),
  ('load-bank-load-factor', 'B', 'It drops to zero', false, 'Load factor never drops in a level turn.', 2, 1),
  ('load-bank-load-factor', 'C', 'It stays at 1 G in any coordinated turn', false, 'Only straight and level flight is 1 G.', 3, 2),
  ('load-bank-load-factor', 'D', 'It increases in a straight line with bank angle', false, 'It rises slowly at first, then steeply.', 4, 3),
  ('load-60-degree-bank', 'A', '2 G', true, null, 1, null::smallint),
  ('load-60-degree-bank', 'B', '60 G', false, 'Load factor is not the bank angle.', 2, 1),
  ('load-60-degree-bank', 'C', '1.15 G', false, 'That is the load factor at 30 degrees.', 3, 2),
  ('load-60-degree-bank', 'D', '1.41 G', false, 'That is the load factor at 45 degrees.', 4, 3),
  ('load-offset-payload', 'A', 'Some motors work harder to hold level, reducing endurance and control margin', true, null, 1, null::smallint),
  ('load-offset-payload', 'B', 'No effect, because the propellers equalize it', false, 'The flight controller compensates by working the motors unevenly.', 2, 1),
  ('load-offset-payload', 'C', 'The aircraft rolls continuously until it lands', false, 'The controller can usually hold level, at a cost.', 3, 2),
  ('load-offset-payload', 'D', 'Endurance improves because the load sits closer to one motor', false, 'Uneven loading costs endurance.', 4, 3),
  ('load-high-elevation', 'A', 'Less thrust per revolution, more motor demand, and shorter flight time', true, null, 1, null::smallint),
  ('load-high-elevation', 'B', 'No change, because Part 107 altitudes are AGL', false, 'Air density depends on actual elevation.', 2, 1),
  ('load-high-elevation', 'C', 'Better performance from lower air resistance', false, 'Lost lift outweighs any drag saving.', 3, 2),
  ('load-high-elevation', 'D', 'Shorter flight time, but more thrust because the air is cooler', false, 'Cooler air partly offsets it, but density is still well below sea level.', 4, 3),
  ('load-voltage-sag', 'A', 'Voltage sags under heavy load, and the aircraft reads it as an empty battery', true, null, 1, null::smallint),
  ('load-voltage-sag', 'B', 'A climb drains exactly 30 percent', false, 'No maneuver drains a fixed percentage.', 2, 1),
  ('load-voltage-sag', 'C', 'The percentage is calculated only at takeoff', false, 'Battery state is monitored throughout flight.', 3, 2),
  ('load-voltage-sag', 'D', 'Cold air raises voltage under load and overloads the controller', false, 'Cold makes sag worse, not better.', 4, 3),
  ('load-wind-limit', 'A', 'Don''t fly; the gusts exceed the published limit', true, null, 1, null::smallint),
  ('load-wind-limit', 'B', 'Fly faster to stay ahead of the wind', false, 'Speed does not solve gusts.', 2, 1),
  ('load-wind-limit', 'C', 'Fly, because the sustained wind is within the limit', false, 'Gusts, not the average, set the risk.', 3, 2),
  ('load-wind-limit', 'D', 'Fly, but stay above 300 feet where gusts smooth out', false, 'Wind is usually stronger, not calmer, with height.', 4, 3),
  ('load-damaged-prop', 'A', 'Less thrust efficiency and vibration that can upset the flight controller', true, null, 1, null::smallint),
  ('load-damaged-prop', 'B', 'It improves airflow', false, 'Damage only degrades a propeller.', 2, 1),
  ('load-damaged-prop', 'C', 'It only affects noise', false, 'Thrust and vibration are affected too.', 3, 2),
  ('load-damaged-prop', 'D', 'Less thrust, but the gimbal fully filters the vibration', false, 'The gimbal steadies the camera, not the flight controller.', 4, 3),
  ('ops-ctaf-inbound-call', 'A', 'To the south, for an aircraft heading toward the airport', true, null, 1, null::smallint),
  ('ops-ctaf-inbound-call', 'B', 'Directly overhead', false, 'It reported 5 miles south.', 2, 1),
  ('ops-ctaf-inbound-call', 'C', 'To the north, since it lands on runway 17', false, 'Its position is south, wherever it lands.', 3, 2),
  ('ops-ctaf-inbound-call', 'D', 'To the south, for an aircraft heading away from the airport', false, 'Inbound means it is heading toward the airport.', 4, 3),
  ('ops-wind-sock', 'A', 'About 15 knots or more', true, null, 1, null::smallint),
  ('ops-wind-sock', 'B', 'Calm', false, 'A calm wind sock hangs limp.', 2, 1),
  ('ops-wind-sock', 'C', 'About 5 knots', false, 'Light wind only partly extends it.', 3, 2),
  ('ops-wind-sock', 'D', 'About 25 knots or more', false, 'Full extension starts at about 15 knots.', 4, 3),
  ('ops-pattern-legs', 'A', 'Upwind, crosswind, downwind, base, final', true, null, 1, null::smallint),
  ('ops-pattern-legs', 'B', 'North, east, south, west', false, 'Pattern legs are named by their relation to the runway.', 2, 1),
  ('ops-pattern-legs', 'C', 'Upwind, downwind, crosswind, base, final', false, 'Crosswind comes before downwind.', 3, 2),
  ('ops-pattern-legs', 'D', 'Upwind, crosswind, base, downwind, final', false, 'Downwind comes before base.', 4, 3),
  ('ops-macho-antidote', 'A', '"Taking chances is foolish."', true, null, 1, null::smallint),
  ('ops-macho-antidote', 'B', '"Fly faster and finish sooner."', false, 'That is not an antidote.', 2, 1),
  ('ops-macho-antidote', 'C', '"Not so fast. Think first."', false, 'That is the antidote to impulsivity.', 3, 2),
  ('ops-macho-antidote', 'D', '"It could happen to me."', false, 'That is the antidote to invulnerability.', 4, 3),
  ('ops-imsafe-s', 'A', 'Stress', true, null, 1, null::smallint),
  ('ops-imsafe-s', 'B', 'Speed', false, 'IMSAFE is about the pilot, not the aircraft.', 2, 1),
  ('ops-imsafe-s', 'C', 'Sobriety', false, 'Sobriety is covered by A, alcohol.', 3, 2),
  ('ops-imsafe-s', 'D', 'Sleep', false, 'Sleep is covered by F, fatigue.', 4, 3),
  ('ops-swollen-lipo', 'A', 'Stop using it and dispose of it through battery recycling', true, null, 1, null::smallint),
  ('ops-swollen-lipo', 'B', 'Press it flat and keep flying', false, 'Compressing a damaged cell can start a fire.', 2, 1),
  ('ops-swollen-lipo', 'C', 'Charge it slowly to reset the cells', false, 'Charging a swollen pack raises the fire risk.', 3, 2),
  ('ops-swollen-lipo', 'D', 'Fly it only for short flights until it fails', false, 'A damaged pack can fail suddenly, even on short flights.', 4, 3),
  ('ops-rth-tree-line', 'A', 'It may fly straight into the trees on its way back', true, null, 1, null::smallint),
  ('ops-rth-tree-line', 'B', 'It hovers in place until the battery runs out', false, 'It flies back, which is the problem.', 2, 1),
  ('ops-rth-tree-line', 'C', 'Obstacle sensors always prevent the collision', false, 'Sensors can miss branches and fail in poor light or when not facing forward.', 3, 2),
  ('ops-rth-tree-line', 'D', 'It climbs to 400 feet automatically before returning', false, 'It climbs only to the altitude you set.', 4, 3),
  ('ops-3p-model', 'A', 'Perceive, Process, Perform', true, null, 1, null::smallint),
  ('ops-3p-model', 'B', 'Pilot, Plane, Passengers', false, 'Those are not the 3P steps.', 2, 1),
  ('ops-3p-model', 'C', 'Plan, Prepare, Proceed', false, 'Those are not the 3P steps.', 3, 2),
  ('ops-3p-model', 'D', 'Perceive, Plan, Perform', false, 'The middle step is Process.', 4, 3),
  ('ops-crew-briefing', 'A', 'Roles, the flight plan, emergency procedures, and agreed calls', true, null, 1, null::smallint),
  ('ops-crew-briefing', 'B', 'Only the client''s shot list', false, 'The shot list leaves out safety.', 2, 1),
  ('ops-crew-briefing', 'C', 'Only the battery swap plan', false, 'That is one part of a briefing.', 3, 2),
  ('ops-crew-briefing', 'D', 'Roles and the flight plan; emergencies are handled as they come', false, 'Emergencies are exactly what the briefing should cover.', 4, 3),
  ('ops-compass-calibration', 'A', 'Nearby metal distorts the magnetic field and corrupts the heading', true, null, 1, null::smallint),
  ('ops-compass-calibration', 'B', 'Calibration only works over grass', false, 'Surface type is not the issue. Nearby metal is.', 2, 1),
  ('ops-compass-calibration', 'C', 'Metal blocks the GPS signals the compass relies on', false, 'The compass senses the magnetic field directly. GPS is separate.', 3, 2),
  ('ops-compass-calibration', 'D', 'Nearby metal shifts the barometric altimeter reading', false, 'Metal affects the compass, not air pressure.', 4, 3)
) as v(slug, label, body, is_correct, rationale, sort_order, tier) on q.slug = v.slug;
